POST http://localhost:8080/pets
Content-Type: application/json

{
  "name": "Rolf",
  "species": "dog",
  "hunger": 70,
  "happiness": 82
}

###

### GET request for pets
GET http://localhost:8080/pets

###
< {%
    request.variables.set("id", "4")
%}
GET http://localhost:8080/pets/{{id}}

###
< {%
    request.variables.set("id", "1")
%}
DELETE http://localhost:8080/pets/{{id}}

###
< {%
    request.variables.set("id", "4")
%}
PUT http://localhost:8080/pets/{{id}}/feed

###
< {%
    request.variables.set("id", "4")
%}
PUT http://localhost:8080/pets/{{id}}/play