### GET request for recipes
GET http://localhost:8080/api/recipes


###
@id =2
GET http://localhost:8080/api/recipes/{{id}}

### Not found
GET http://localhost:8080/api/recipes/-10

###
POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "title": "Bacon and Eggs",
  "instructions": "Fry the eggs first",
  "items": [
    {
      "name": "Bacon",
      "amount": 200,
      "unit": "g"
    },
    {
      "name": "Eggs",
      "amount": 2,
      "unit": "pcs"
    }
  ]
}

### Error
POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "title": "",
  "instructions": "",
  "items": [
    {
      "name": "",
      "amount": -1,
      "unit": ""
    }
  ]
}

### Duplicated title
POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "title": "Bacon and Eggs",
  "instructions": "Fry the eggs first",
  "items": [
    {
      "name": "Bacon",
      "amount": 200,
      "unit": "g"
    },
    {
      "name": "Eggs",
      "amount": 2,
      "unit": "pcs"
    }
  ]
}
