### Login
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

###GET all stores

GET http://localhost:8080/api/stores

### GET store depending on author in stock
@author =Sofia

GET http://localhost:8080/api/stores/author/{{author}}

### GET store by name
@name =Books of books
 
GET http://localhost:8080/api/stores/{{name}}