spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_only

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  # Kontrollera att Flyway-schemat matchar entiteterna
    properties:
      hibernate:
        format_sql: true

  flyway:
    validate-on-migrate: true