spring.application.name=exercise2025
spring.threads.virtual.enabled=true
spring.web.resources.cache.period=0
spring.thymeleaf.cache=false
# Run application
#spring.datasource.url=jdbc:mysql://localhost:3306/books
#spring.datasource.username=${DATABASE_USER:customizedUser}
#spring.datasource.password=${DATABASE_PASSWORD:secret}
