spring:
  jpa:
    hibernate:
      ddl-auto: none
  main:
    web-application-type: servlet
  application:
    name: exercise2025
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/exercise2025?useSSL=false&serverTimezone=UTC
    username: root
    password: secret
  security:
    user:
      name: admin
      password: admin123

