spring.application.name=exercise2025
spring.threads.virtual.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=secret
# spring.jpa.hibernate.ddl-auto=update
