### Add a Director
POST http://localhost:8080/api/director
Content-Type: application/json
X-API-KEY: 123

{
  "firstName": "Alfred",
  "lastName": "Brännare",
  "movies": [
    {
      "title": "Spring Boot the Movie",
      "duration": 120,
      "genre": "Action"
    },
    {
      "title": "Spring Boot the Movie 2",
      "duration": 240,
      "genre": "Action/Comedy"
    }
  ]
}

### Get All Directors
GET http://localhost:8080/api/director
Content-Type: application/json
X-API-KEY: 123

### Get Director By Id
GET http://localhost:8080/api/director/3
Content-Type: application/json
X-API-KEY: 123

### Update Director
PUT http://localhost:8080/api/director/3
Content-Type: application/json
X-API-KEY: 123

{
  "firstName": "Derfla"
}

### Delete Director
DELETE http://localhost:8080/api/director/2
Content-Type: application/json
X-API-KEY: 123
