### Add a Movie
POST http://localhost:8080/api/movie
Content-Type: application/json
X-API-KEY: 123

{
  "title": "Some Movie",
  "genre": "Action",
  "duration": 120,
  "directorId": 1
}

### Get All Movies
GET http://localhost:8080/api/movie
Content-Type: application/json
X-API-KEY: 123

### Get Movie By Id
GET http://localhost:8080/api/movie/1
Content-Type: application/json
X-API-KEY: 123

### Update Movie
PUT http://localhost:8080/api/movie/10
Content-Type: application/json
X-API-KEY: 123

{
  "title": "Boot Spring the Movie",
  "duration": 1337,
  "genre": "Test"
}

### Delete Movie
DELETE http://localhost:8080/api/movie/1
Content-Type: application/json
X-API-KEY: 123