/** Needs to match my quote entity **/
CREATE TABLE quotes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote          VARCHAR(255),
    movie          VARCHAR(255),
    character_name VARCHAR(255),
    release_year   INT
);
